# Testing the new version of `pbcpy`

write simple tests here, that will be then implemented in the proper unit tests


In [1]:
import numpy as np
import sys
if "../src/" not in sys.path:
    sys.path.insert(0,"../src/")
from pbcpy.base import DirectCell, ReciprocalCell, Coord
from pbcpy.grid import DirectGrid, ReciprocalGrid
%load_ext autoreload
%autoreload 2

In [42]:
at1 = np.identity(3)*10
cell1 = DirectCell(lattice=at1, origin=[0,0,0], units="Angstrom") # 10A cubic cell

In [43]:
cell1.lattice

array([[ 18.89726125,   0.        ,   0.        ],
       [  0.        ,  18.89726125,   0.        ],
       [  0.        ,   0.        ,  18.89726125]])

In [44]:
cell1.volume

6748.3345034684608

In [45]:
rcell = cell1.get_reciprocal()

In [46]:
rcell.lattice

array([[ 0.17594711,  0.        ,  0.        ],
       [ 0.        ,  0.17594711,  0.        ],
       [ 0.        ,  0.        ,  0.17594711]])

In [47]:
dcell = rcell.get_direct()

In [48]:
print(dcell==cell1)

False


In [49]:
type(cell1), type(dcell)

(pbcpy.base.DirectCell, pbcpy.base.DirectCell)

In [50]:
dcell.lattice

array([[ 1.7093731,  0.       ,  0.       ],
       [ 0.       ,  1.7093731,  0.       ],
       [ 0.       ,  0.       ,  1.7093731]])

In [52]:
all(cell1.lattice==at1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [62]:
at1 = np.identity(3)*10
cell1 = DirectGrid(lattice=at1, origin=[0,0,0], nr=[8,8,8]) # 10A cubic cell

In [63]:
cell1.r[0,0,1,:]

Coord([ 0.  ,  0.  ,  1.25])

In [64]:
reciprocal = cell1.get_reciprocal()

In [66]:
g = reciprocal.g

In [69]:
gg=np.einsum("ijkl,ijkl->ijk",g,g)

In [74]:
gg[0,0,1], g[0,0,1,:], 0.125**2

(0.015625, array([ 0.   ,  0.   ,  0.125]), 0.015625)