# Testing the new version of `pbcpy`

write simple tests here, that will be then implemented in the proper unit tests


In [1]:
import numpy as np
import sys
if "../src/" not in sys.path:
    sys.path.insert(0,"../src/")
from pbcpy.base import DirectCell, ReciprocalCell, Coord
from pbcpy.grid import DirectGrid, ReciprocalGrid
%load_ext autoreload
%autoreload 2

In [2]:
at1 = np.identity(3)*10
cell1 = DirectCell(lattice=at1, origin=[0,0,0], units="Angstrom") # 10A cubic cell

WARN


In [3]:
cell1.lattice

array([[ 10.,   0.,   0.],
       [  0.,  10.,   0.],
       [  0.,   0.,  10.]])

In [44]:
cell1.volume

6748.3345034684608

In [45]:
rcell = cell1.get_reciprocal()

In [46]:
rcell.lattice

array([[ 0.17594711,  0.        ,  0.        ],
       [ 0.        ,  0.17594711,  0.        ],
       [ 0.        ,  0.        ,  0.17594711]])

In [47]:
dcell = rcell.get_direct()

In [48]:
print(dcell==cell1)

False


In [49]:
type(cell1), type(dcell)

(pbcpy.base.DirectCell, pbcpy.base.DirectCell)

In [50]:
dcell.lattice

array([[ 1.7093731,  0.       ,  0.       ],
       [ 0.       ,  1.7093731,  0.       ],
       [ 0.       ,  0.       ,  1.7093731]])

In [52]:
all(cell1.lattice==at1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [62]:
at1 = np.identity(3)*10
cell1 = DirectGrid(lattice=at1, origin=[0,0,0], nr=[8,8,8]) # 10A cubic cell

In [63]:
cell1.r[0,0,1,:]

Coord([ 0.  ,  0.  ,  1.25])

In [64]:
reciprocal = cell1.get_reciprocal()

In [66]:
g = reciprocal.g

In [69]:
gg=np.einsum("ijkl,ijkl->ijk",g,g)

In [4]:
gg[0,0,1], g[0,0,1,:], 0.125**2

NameError: name 'gg' is not defined

In [11]:
from pbcpy.formats.qepp import PP

In [12]:
water_dimer = PP(filepp="../tests/density_ks.pp").read()

In [13]:
water_dimer.field.gradient()

../src/pbcpy/field.py:105: ComplexWarning: Casting complex values to real discards the imaginary part
  grad_g[...,i] = reciprocal.grid.g[...,i] * (reciprocal[...,0]*imag)


DirectField([[[[  5.68148369e-09 +0.00000000e+00j,
            6.50807566e-09 +0.00000000e+00j,
           -2.13940650e-09 +0.00000000e+00j],
         [  2.17623941e-09 -8.42103689e-21j,
            3.58403046e-09 -2.67215365e-20j,
            1.14688585e-09 -1.17246858e-19j],
         [ -1.36259565e-09 +3.53215303e-20j,
           -1.89011269e-09 -3.70856438e-20j,
           -1.13867886e-09 -1.93005457e-19j],
         ..., 
         [  3.14968211e-10 -7.93425109e-21j,
           -1.71386134e-09 +1.14349633e-19j,
            5.89412476e-10 +2.03516231e-19j],
         [ -1.36259565e-09 -9.48824891e-20j,
           -1.89011269e-09 +9.03013089e-20j,
           -1.13867886e-09 +1.72004836e-19j],
         [  2.17623941e-09 -3.33404214e-20j,
            3.58403046e-09 +7.77569321e-20j,
            1.14688585e-09 +1.93684999e-20j]],

        [[  1.42216420e-09 +1.22691787e-19j,
           -2.12629377e-09 +3.68892890e-20j,
           -3.57873834e-10 +2.00876715e-21j],
         [ -6.75879364e-0

In [4]:
rho_g = water_dimer.field.fft()

In [7]:
rho_g.grid.g[...,2].shape

(125, 125, 125)

In [10]:
(rho_g.grid.g[...,1]*rho_g[...,0]).shape

(125, 125, 125)