In [62]:
import numpy as np
from pbcpy.base import Cell
from pbcpy.grid import Grid, ReciprocalGrid, Grid_Function

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
at = np.identity(3)
at[0][0]=2
at[1][1]=3
cell = Cell(at)
print(cell.bg)
print('----------------')
print(cell.at)

[[ 0.5         0.          0.        ]
 [ 0.          0.33333333  0.        ]
 [ 0.          0.          1.        ]]
----------------
[[ 2.  0.  0.]
 [ 0.  3.  0.]
 [ 0.  0.  1.]]


In [60]:
nr = [2,2,3]
grid = Grid(at, nr)
invgrid = ReciprocalGrid(grid.bg,nr)

In [51]:
invgrid.omega, grid.omega

(0.16666666666666666, 6.0)

In [61]:
print(grid.units)
print(grid.r)
print(grid.a)

Bohr
[[[[ 0.          0.          0.        ]
   [ 0.          0.          0.33333333]
   [ 0.          0.          0.66666667]]

  [[ 0.          1.5         0.        ]
   [ 0.          1.5         0.33333333]
   [ 0.          1.5         0.66666667]]]


 [[[ 1.          0.          0.        ]
   [ 1.          0.          0.33333333]
   [ 1.          0.          0.66666667]]

  [[ 1.          1.5         0.        ]
   [ 1.          1.5         0.33333333]
   [ 1.          1.5         0.66666667]]]]
[[[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.5         0.5         0.5       ]
  [ 0.5         0.5         0.5       ]]

 [[ 0.          0.          0.        ]
  [ 0.5         0.5         0.5       ]]

 [[ 0.          0.          0.        ]
  [ 0.5         0.5         0.5       ]]

 [[ 0.          0.33333333  0.66666667]
  [ 0.          0.33333333  0.66666667]]

 [[ 0.          0.33333333  0.66666667]
  [ 0.          0.33333333  0.66666667]]]


In [ ]:
pl = Grid_Function(grid=grid,)

In [33]:
np.fft.fftfreq(10),np.fft.fftfreq(11,)

(array([ 0. ,  0.1,  0.2,  0.3,  0.4, -0.5, -0.4, -0.3, -0.2, -0.1]),
 array([ 0.        ,  0.09090909,  0.18181818,  0.27272727,  0.36363636,
         0.45454545, -0.45454545, -0.36363636, -0.27272727, -0.18181818,
        -0.09090909]))