In [25]:
import numpy as np
from pbcpy.grid import Grid_Space, Grid_Function, Grid_Function_Reciprocal
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [26]:
at = np.identity(3)
at[0][0]=2

In [39]:
nr = [5,1,1]
grid = Grid_Space(at, nr)

In [67]:
dist_f = grid.dist_func()
sqrdist_f = grid.sqr_dist_func()
print(dist_f.values)
print(sqrdist_f.values)

[[[ 0. ]]

 [[ 0.4]]

 [[ 0.8]]

 [[ 1.2]]

 [[ 1.6]]]
[[[ 0.  ]]

 [[ 0.16]]

 [[ 0.64]]

 [[ 1.44]]

 [[ 2.56]]]


In [70]:
dist_f.linear_combination(sqrdist_f,2,2).values

array([[[ 0.  ]],

       [[ 1.12]],

       [[ 2.88]],

       [[ 5.28]],

       [[ 8.32]]])

## dist_f.integral()

In [48]:
dist_f.dotCnst(2).values

array([[[ 0.  ]],

       [[ 0.32]],

       [[ 1.28]],

       [[ 2.88]],

       [[ 5.12]]])

In [49]:
dist_f.sumCnst(2).values

array([[[ 2.  ]],

       [[ 2.16]],

       [[ 2.64]],

       [[ 3.44]],

       [[ 4.56]]])